insert into barang (id, nama, satuan, stok) values (1, 'Butter - Salted', 'c', 63);
insert into barang (id, nama, satuan, stok) values (2, 'Cumin - Whole', 'HGp', 100);
insert into barang (id, nama, satuan, stok) values (3, 'Cheese - Cheddar With Claret', 'YiI', 52);
insert into barang (id, nama, satuan, stok) values (4, 'Turkey Leg With Drum And Thigh', 'Lw', 84);
insert into barang (id, nama, satuan, stok) values (5, 'Rum - White, Gg White', 'AS', 87);
insert into barang (id, nama, satuan, stok) values (6, 'Beef - Shank', 'uPo', 100);
insert into barang (id, nama, satuan, stok) values (7, 'Syrup - Chocolate', 'sRe', 3);
insert into barang (id, nama, satuan, stok) values (8, 'Sambuca - Opal Nera', 'bxD', 20);
insert into barang (id, nama, satuan, stok) values (9, 'Tequila - Sauza Silver', 'iZ', 78);
insert into barang (id, nama, satuan, stok) values (10, 'Venison - Ground', 'z', 66);
insert into barang (id, nama, satuan, stok) values (11, 'Salmon Atl.whole 8 - 10 Lb', 't', 56);
insert into barang (id, nama, satuan, stok) values (12, 'Wine - Savigny - Les - Beaune', 'MUw', 20);
insert into barang (id, nama, satuan, stok) values (13, 'Langers - Cranberry Cocktail', 'x', 1);
insert into barang (id, nama, satuan, stok) values (14, 'Kellogs Raisan Bran Bars', 'jA', 31);
insert into barang (id, nama, satuan, stok) values (15, 'Cheese - Cottage Cheese', 'rbi', 44);
insert into barang (id, nama, satuan, stok) values (16, 'Ecolab - Mikroklene 4/4 L', 'wm', 89);
insert into barang (id, nama, satuan, stok) values (17, 'Garlic - Elephant', 'xI', 77);
insert into barang (id, nama, satuan, stok) values (18, 'Cheese - Mozzarella', 'AO', 30);
insert into barang (id, nama, satuan, stok) values (19, 'Aromat Spice / Seasoning', 'tyk', 53);
insert into barang (id, nama, satuan, stok) values (20, 'Bagel - Ched Chs Presliced', 'ZUh', 76);
insert into barang (id, nama, satuan, stok) values (21, 'Water - Mineral, Carbonated', 'QSn', 78);
insert into barang (id, nama, satuan, stok) values (22, 'Cheese - Brie,danish', 'EC', 97);
insert into barang (id, nama, satuan, stok) values (23, 'Bread Sour Rolls', 'KsH', 67);
insert into barang (id, nama, satuan, stok) values (24, 'Pasta - Fusili, Dry', 'sY', 55);
insert into barang (id, nama, satuan, stok) values (25, 'Split Peas - Green, Dry', 'vTQ', 43);
insert into barang (id, nama, satuan, stok) values (26, 'Chef Hat 20cm', 'CIc', 81);
insert into barang (id, nama, satuan, stok) values (27, 'Salt - Kosher', 'u', 46);
insert into barang (id, nama, satuan, stok) values (28, 'Barley - Pearl', 'gBE', 6);
insert into barang (id, nama, satuan, stok) values (29, 'Guinea Fowl', 'rg', 82);
insert into barang (id, nama, satuan, stok) values (30, 'Soup - Campbells Broccoli', 'D', 15);
insert into barang (id, nama, satuan, stok) values (31, 'Potatoes - Parissienne', 'sS', 89);
insert into barang (id, nama, satuan, stok) values (32, 'Yeast - Fresh, Fleischman', 'p', 95);
insert into barang (id, nama, satuan, stok) values (33, 'Flour - Rye', 'k', 72);
insert into barang (id, nama, satuan, stok) values (34, 'Cucumber - English', 'r', 24);
insert into barang (id, nama, satuan, stok) values (35, 'Paper Towel Touchless', 'af', 29);
insert into barang (id, nama, satuan, stok) values (36, 'Red Currant Jelly', 'P', 42);
insert into barang (id, nama, satuan, stok) values (37, 'Coffee Swiss Choc Almond', 'F', 24);
insert into barang (id, nama, satuan, stok) values (38, 'Horseradish Root', 'eT', 61);
insert into barang (id, nama, satuan, stok) values (39, 'Sea Bass - Fillets', 'Ll', 73);
insert into barang (id, nama, satuan, stok) values (40, 'Cake - Mini Cheesecake', 'qAk', 38);
insert into barang (id, nama, satuan, stok) values (41, 'Soup - French Onion', 'BsY', 51);
insert into barang (id, nama, satuan, stok) values (42, 'Snapple Lemon Tea', 'Fw', 88);
insert into barang (id, nama, satuan, stok) values (43, 'Fuji Apples', 'i', 26);
insert into barang (id, nama, satuan, stok) values (44, 'Mayonnaise - Individual Pkg', 'gv', 40);
insert into barang (id, nama, satuan, stok) values (45, 'Olives - Green, Pitted', 'N', 27);
insert into barang (id, nama, satuan, stok) values (46, 'Tomato - Green', 'NKs', 30);
insert into barang (id, nama, satuan, stok) values (47, 'Persimmons', 'rkL', 52);
insert into barang (id, nama, satuan, stok) values (48, 'Nut - Almond, Blanched, Sliced', 'Cc', 93);
insert into barang (id, nama, satuan, stok) values (49, 'Higashimaru Usukuchi Soy', 'GP', 32);
insert into barang (id, nama, satuan, stok) values (50, 'Easy Off Oven Cleaner', 'Xx', 77);
