insert into barang (id, nama, satuan, stok, harga) values (1, 'Butter - Salted', 'c', 63, 10000);
insert into barang (id, nama, satuan, stok, harga) values (2, 'Cumin - Whole', 'HGp', 100, 10000);
insert into barang (id, nama, satuan, stok, harga) values (3, 'Cheese - Cheddar With Claret', 'YiI', 52, 10000);
insert into barang (id, nama, satuan, stok, harga) values (4, 'Turkey Leg With Drum And Thigh', 'Lw', 84, 10000);
insert into barang (id, nama, satuan, stok, harga) values (5, 'Rum - White, Gg White', 'AS', 87, 10000);
insert into barang (id, nama, satuan, stok, harga) values (6, 'Beef - Shank', 'uPo', 100, 10000);
insert into barang (id, nama, satuan, stok, harga) values (7, 'Syrup - Chocolate', 'sRe', 3, 10000);
insert into barang (id, nama, satuan, stok, harga) values (8, 'Sambuca - Opal Nera', 'bxD', 20, 10000);
insert into barang (id, nama, satuan, stok, harga) values (9, 'Tequila - Sauza Silver', 'iZ', 78, 10000);
insert into barang (id, nama, satuan, stok, harga) values (10, 'Venison - Ground', 'z', 66, 10000);
insert into barang (id, nama, satuan, stok, harga) values (11, 'Salmon Atl.whole 8 - 10 Lb', 't', 56, 10000);
insert into barang (id, nama, satuan, stok, harga) values (12, 'Wine - Savigny - Les - Beaune', 'MUw', 20, 10000);
insert into barang (id, nama, satuan, stok, harga) values (13, 'Langers - Cranberry Cocktail', 'x', 1, 10000);
insert into barang (id, nama, satuan, stok, harga) values (14, 'Kellogs Raisan Bran Bars', 'jA', 31, 10000);
insert into barang (id, nama, satuan, stok, harga) values (15, 'Cheese - Cottage Cheese', 'rbi', 44, 10000);
insert into barang (id, nama, satuan, stok, harga) values (16, 'Ecolab - Mikroklene 4/4 L', 'wm', 89, 10000);
insert into barang (id, nama, satuan, stok, harga) values (17, 'Garlic - Elephant', 'xI', 77, 10000);
insert into barang (id, nama, satuan, stok, harga) values (18, 'Cheese - Mozzarella', 'AO', 30, 10000);
insert into barang (id, nama, satuan, stok, harga) values (19, 'Aromat Spice / Seasoning', 'tyk', 53, 10000);
insert into barang (id, nama, satuan, stok, harga) values (20, 'Bagel - Ched Chs Presliced', 'ZUh', 76, 10000);
insert into barang (id, nama, satuan, stok, harga) values (21, 'Water - Mineral, Carbonated', 'QSn', 78, 10000);
insert into barang (id, nama, satuan, stok, harga) values (22, 'Cheese - Brie,danish', 'EC', 97, 10000);
insert into barang (id, nama, satuan, stok, harga) values (23, 'Bread Sour Rolls', 'KsH', 67, 10000);
insert into barang (id, nama, satuan, stok, harga) values (24, 'Pasta - Fusili, Dry', 'sY', 55, 10000);
insert into barang (id, nama, satuan, stok, harga) values (25, 'Split Peas - Green, Dry', 'vTQ', 43, 10000);
insert into barang (id, nama, satuan, stok, harga) values (26, 'Chef Hat 20cm', 'CIc', 81, 10000);
insert into barang (id, nama, satuan, stok, harga) values (27, 'Salt - Kosher', 'u', 46, 10000);
insert into barang (id, nama, satuan, stok, harga) values (28, 'Barley - Pearl', 'gBE', 6, 10000);
insert into barang (id, nama, satuan, stok, harga) values (29, 'Guinea Fowl', 'rg', 82, 10000);
insert into barang (id, nama, satuan, stok, harga) values (30, 'Soup - Campbells Broccoli', 'D', 15, 10000);
insert into barang (id, nama, satuan, stok, harga) values (31, 'Potatoes - Parissienne', 'sS', 89, 10000);
insert into barang (id, nama, satuan, stok, harga) values (32, 'Yeast - Fresh, Fleischman', 'p', 95, 10000);
insert into barang (id, nama, satuan, stok, harga) values (33, 'Flour - Rye', 'k', 72, 10000);
insert into barang (id, nama, satuan, stok, harga) values (34, 'Cucumber - English', 'r', 24, 10000);
insert into barang (id, nama, satuan, stok, harga) values (35, 'Paper Towel Touchless', 'af', 29, 10000);
insert into barang (id, nama, satuan, stok, harga) values (36, 'Red Currant Jelly', 'P', 42, 10000);
insert into barang (id, nama, satuan, stok, harga) values (37, 'Coffee Swiss Choc Almond', 'F', 24, 10000);
insert into barang (id, nama, satuan, stok, harga) values (38, 'Horseradish Root', 'eT', 61, 10000);
insert into barang (id, nama, satuan, stok, harga) values (39, 'Sea Bass - Fillets', 'Ll', 73, 10000);
insert into barang (id, nama, satuan, stok, harga) values (40, 'Cake - Mini Cheesecake', 'qAk', 38, 10000);
insert into barang (id, nama, satuan, stok, harga) values (41, 'Soup - French Onion', 'BsY', 51, 10000);
insert into barang (id, nama, satuan, stok, harga) values (42, 'Snapple Lemon Tea', 'Fw', 88, 10000);
insert into barang (id, nama, satuan, stok, harga) values (43, 'Fuji Apples', 'i', 26, 10000);
insert into barang (id, nama, satuan, stok, harga) values (44, 'Mayonnaise - Individual Pkg', 'gv', 40, 10000);
insert into barang (id, nama, satuan, stok, harga) values (45, 'Olives - Green, Pitted', 'N', 27, 10000);
insert into barang (id, nama, satuan, stok, harga) values (46, 'Tomato - Green', 'NKs', 30, 10000);
insert into barang (id, nama, satuan, stok, harga) values (47, 'Persimmons', 'rkL', 52, 10000);
insert into barang (id, nama, satuan, stok, harga) values (48, 'Nut - Almond, Blanched, Sliced', 'Cc', 93, 10000);
insert into barang (id, nama, satuan, stok, harga) values (49, 'Higashimaru Usukuchi Soy', 'GP', 32, 10000);
insert into barang (id, nama, satuan, stok, harga) values (50, 'Easy Off Oven Cleaner', 'Xx', 77, 10000);
