insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (1, 'Simonette', 'Charlotte Amalie', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam', '2017-02-20');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (2, 'Robby', 'Miedzichowo', 'bibendum felis sed interdum venenatis turpis enim blandit', '2017-04-22');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (3, 'Arthur', 'Svoge', 'massa id lobortis convallis tortor risus dapibus augue vel accumsan', '2016-11-11');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (4, 'Derrick', 'Västra Frölunda', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', '2017-06-25');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (5, 'Corrianne', 'Daraitan', 'posuere cubilia curae mauris viverra diam vitae', '2017-07-09');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (6, 'Bendix', 'Santana', 'nec nisi volutpat eleifend donec ut dolor', '2016-12-22');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (7, 'Eleanora', 'Kveda Chkhorots’q’u', 'in tempus sit amet sem fusce consequat', '2017-04-18');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (8, 'Mathias', 'Tam Bình', 'pede libero quis orci nullam molestie nibh in lectus', '2016-11-17');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (9, 'Dayle', 'Guarujá', 'aenean lectus pellentesque eget nunc donec', '2017-04-20');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (10, 'Abigale', 'Al Mālikīyah', 'non mi integer ac neque duis bibendum morbi', '2016-12-03');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (11, 'Wallis', 'Balatero', 'donec dapibus duis at velit eu est', '2016-09-22');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (12, 'Ros', 'Narsaq', 'sapien arcu sed augue aliquam', '2017-06-14');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (13, 'Marcia', 'Beloha', 'eros suspendisse accumsan tortor quis turpis sed', '2016-10-04');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (14, 'Cherrita', 'Wolbrom', 'venenatis tristique fusce congue diam id', '2016-10-23');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (15, 'Lanny', 'Prado', 'dictumst etiam faucibus cursus urna ut tellus nulla', '2017-03-13');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (16, 'April', 'Old Harbour Bay', 'risus dapibus augue vel accumsan tellus nisi eu', '2017-06-15');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (17, 'Dud', 'Brandsen', 'felis ut at dolor quis odio consequat varius integer', '2017-07-04');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (18, 'Walden', 'João Pessoa', 'pellentesque eget nunc donec quis orci eget orci', '2017-05-26');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (19, 'Odella', 'Årjäng', 'rutrum rutrum neque aenean auctor gravida', '2016-12-04');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (20, 'Hertha', 'San Miguel', 'libero quis orci nullam molestie nibh in lectus pellentesque', '2017-03-11');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (21, 'Irwinn', 'Peristerá', 'in consequat ut nulla sed accumsan', '2017-06-20');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (22, 'Jojo', 'Wumahe', 'quisque erat eros viverra eget congue eget', '2017-07-15');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (23, 'Cody', 'Kapakabisa', 'nulla ultrices aliquet maecenas leo odio', '2017-01-10');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (24, 'Rice', 'Quinua', 'elementum nullam varius nulla facilisi cras', '2017-04-09');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (25, 'Maryellen', 'Kalipare', 'quam pede lobortis ligula sit', '2016-12-21');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (26, 'Kelvin', 'Altavista', 'vestibulum velit id pretium iaculis diam erat', '2017-03-25');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (27, 'Rabi', 'Cần Giờ', 'nulla mollis molestie lorem quisque ut erat curabitur', '2016-12-18');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (28, 'Morly', 'Tolomango', 'nisi nam ultrices libero non mattis', '2017-04-22');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (29, 'Benedikt', 'Descalvado', 'integer ac neque duis bibendum morbi non quam nec dui', '2016-10-26');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (30, 'Sayre', 'Sarana', 'volutpat quam pede lobortis ligula', '2016-11-14');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (31, 'Quent', 'Busia', 'luctus ultricies eu nibh quisque id', '2017-04-13');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (32, 'Zonda', 'Nový Bydžov', 'lectus aliquam sit amet diam', '2017-04-28');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (33, 'Ginger', 'Chimichagua', 'nisi at nibh in hac habitasse platea', '2017-03-01');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (34, 'Sheila-kathryn', 'Athabasca', 'ac consequat metus sapien ut nunc vestibulum', '2017-07-29');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (35, 'Burch', 'Starý Bohumín', 'aenean sit amet justo morbi', '2017-06-02');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (36, 'Rik', 'Arnhem', 'eget tincidunt eget tempus vel pede morbi porttitor', '2016-10-21');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (37, 'Thaddeus', 'Himeji', 'suspendisse potenti in eleifend quam', '2017-07-10');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (38, 'Pamella', 'Limoges', 'turpis eget elit sodales scelerisque', '2017-08-12');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (39, 'Dael', 'Estancia', 'posuere nonummy integer non velit', '2017-06-05');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (40, 'Tate', 'Mulandoro', 'at dolor quis odio consequat varius integer ac leo', '2017-05-25');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (41, 'Desiri', 'La Falda', 'felis donec semper sapien a libero', '2016-10-08');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (42, 'Coop', 'Vohibinany', 'ut erat curabitur gravida nisi at nibh in', '2017-04-14');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (43, 'Giacobo', 'København', 'eget tincidunt eget tempus vel pede morbi', '2016-09-08');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (44, 'Cathi', 'Aihua', 'nullam sit amet turpis elementum ligula vehicula consequat', '2017-07-17');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (45, 'Arnuad', 'Krasnoyarka', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu', '2017-07-12');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (46, 'Eduino', 'Jaffna', 'tincidunt nulla mollis molestie lorem quisque ut', '2017-07-27');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (47, 'Consalve', 'Masalovka', 'pharetra magna vestibulum aliquet ultrices erat tortor', '2017-08-20');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (48, 'Linnie', 'Zabukovica', 'porttitor lacus at turpis donec posuere metus vitae', '2017-05-07');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (49, 'Ella', 'Trà Ôn', 'dolor sit amet consectetuer adipiscing', '2016-09-18');
insert into proyek (id, nama, lokasi, deskripsi, tanggal_mulai) values (50, 'Ibby', 'Dallas', 'bibendum imperdiet nullam orci pede venenatis non sodales sed', '2017-02-03');
